<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('countries')->delete();

        $countries = array(
            array('id' => '1', 'name' => 'Afghanistan', 'shortname' => 'AF', 'phonecode' => '93', 'is_active' => '1'),
            array('id' => '2', 'name' => 'Albania', 'shortname' => 'AL', 'phonecode' => '355', 'is_active' => '1'),
            array('id' => '3', 'name' => 'Algeria', 'shortname' => 'DZ', 'phonecode' => '213', 'is_active' => '1'),
            array('id' => '4', 'name' => 'American Samoa', 'shortname' => 'AS', 'phonecode' => '1684', 'is_active' => '1'),
            array('id' => '5', 'name' => 'Andorra', 'shortname' => 'AD', 'phonecode' => '376', 'is_active' => '1'),
            array('id' => '6', 'name' => 'Angola', 'shortname' => 'AO', 'phonecode' => '244', 'is_active' => '1'),
            array('id' => '7', 'name' => 'Anguilla', 'shortname' => 'AI', 'phonecode' => '1264', 'is_active' => '1'),
            array('id' => '8', 'name' => 'Antarctica', 'shortname' => 'AQ', 'phonecode' => '0', 'is_active' => '1'),
            array('id' => '9', 'name' => 'Antigua And Barbuda', 'shortname' => 'AG', 'phonecode' => '1268', 'is_active' => '1'),
            array('id' => '10', 'name' => 'Argentina', 'shortname' => 'AR', 'phonecode' => '54', 'is_active' => '1'),
            array('id' => '11', 'name' => 'Armenia', 'shortname' => 'AM', 'phonecode' => '374', 'is_active' => '1'),
            array('id' => '12', 'name' => 'Aruba', 'shortname' => 'AW', 'phonecode' => '297', 'is_active' => '1'),
            array('id' => '13', 'name' => 'Australia', 'shortname' => 'AU', 'phonecode' => '61', 'is_active' => '1'),
            array('id' => '14', 'name' => 'Austria', 'shortname' => 'AT', 'phonecode' => '43', 'is_active' => '1'),
            array('id' => '15', 'name' => 'Azerbaijan', 'shortname' => 'AZ', 'phonecode' => '994', 'is_active' => '1'),
            array('id' => '16', 'name' => 'Bahamas', 'shortname' => 'BS', 'phonecode' => '1242', 'is_active' => '1'),
            array('id' => '17', 'name' => 'Bahrain', 'shortname' => 'BH', 'phonecode' => '973', 'is_active' => '1'),
            array('id' => '18', 'name' => 'Bangladesh', 'shortname' => 'BD', 'phonecode' => '880', 'is_active' => '1'),
            array('id' => '19', 'name' => 'Barbados', 'shortname' => 'BB', 'phonecode' => '1246', 'is_active' => '1'),
            array('id' => '20', 'name' => 'Belarus', 'shortname' => 'BY', 'phonecode' => '375', 'is_active' => '1'),
            array('id' => '21', 'name' => 'Belgium', 'shortname' => 'BE', 'phonecode' => '32', 'is_active' => '1'),
            array('id' => '22', 'name' => 'Belize', 'shortname' => 'BZ', 'phonecode' => '501', 'is_active' => '1'),
            array('id' => '23', 'name' => 'Benin', 'shortname' => 'BJ', 'phonecode' => '229', 'is_active' => '1'),
            array('id' => '24', 'name' => 'Bermuda', 'shortname' => 'BM', 'phonecode' => '1441', 'is_active' => '1'),
            array('id' => '25', 'name' => 'Bhutan', 'shortname' => 'BT', 'phonecode' => '975', 'is_active' => '1'),
            array('id' => '26', 'name' => 'Bolivia', 'shortname' => 'BO', 'phonecode' => '591', 'is_active' => '1'),
            array('id' => '27', 'name' => 'Bosnia and Herzegovina', 'shortname' => 'BA', 'phonecode' => '387', 'is_active' => '1'),
            array('id' => '28', 'name' => 'Botswana', 'shortname' => 'BW', 'phonecode' => '267', 'is_active' => '1'),
            array('id' => '29', 'name' => 'Bouvet Island', 'shortname' => 'BV', 'phonecode' => '0', 'is_active' => '1'),
            array('id' => '30', 'name' => 'Brazil', 'shortname' => 'BR', 'phonecode' => '55', 'is_active' => '1'),
            array('id' => '31', 'name' => 'British Indian Ocean Territory', 'shortname' => 'IO', 'phonecode' => '246', 'is_active' => '1'),
            array('id' => '32', 'name' => 'Brunei', 'shortname' => 'BN', 'phonecode' => '673', 'is_active' => '1'),
            array('id' => '33', 'name' => 'Bulgaria', 'shortname' => 'BG', 'phonecode' => '359', 'is_active' => '1'),
            array('id' => '34', 'name' => 'Burkina Faso', 'shortname' => 'BF', 'phonecode' => '226', 'is_active' => '1'),
            array('id' => '35', 'name' => 'Burundi', 'shortname' => 'BI', 'phonecode' => '257', 'is_active' => '1'),
            array('id' => '36', 'name' => 'Cambodia', 'shortname' => 'KH', 'phonecode' => '855', 'is_active' => '1'),
            array('id' => '37', 'name' => 'Cameroon', 'shortname' => 'CM', 'phonecode' => '237', 'is_active' => '1'),
            array('id' => '38', 'name' => 'Canada', 'shortname' => 'CA', 'phonecode' => '1', 'is_active' => '1'),
            array('id' => '39', 'name' => 'Cape Verde', 'shortname' => 'CV', 'phonecode' => '238', 'is_active' => '1'),
            array('id' => '40', 'name' => 'Cayman Islands', 'shortname' => 'KY', 'phonecode' => '1345', 'is_active' => '1'),
            array('id' => '41', 'name' => 'Central African Republic', 'shortname' => 'CF', 'phonecode' => '236', 'is_active' => '1'),
            array('id' => '42', 'name' => 'Chad', 'shortname' => 'TD', 'phonecode' => '235', 'is_active' => '1'),
            array('id' => '43', 'name' => 'Chile', 'shortname' => 'CL', 'phonecode' => '56', 'is_active' => '1'),
            array('id' => '44', 'name' => 'China', 'shortname' => 'CN', 'phonecode' => '86', 'is_active' => '1'),
            array('id' => '45', 'name' => 'Christmas Island', 'shortname' => 'CX', 'phonecode' => '61', 'is_active' => '1'),
            array('id' => '46', 'name' => 'Cocos (Keeling) Islands', 'shortname' => 'CC', 'phonecode' => '672', 'is_active' => '1'),
            array('id' => '47', 'name' => 'Colombia', 'shortname' => 'CO', 'phonecode' => '57', 'is_active' => '1'),
            array('id' => '48', 'name' => 'Comoros', 'shortname' => 'KM', 'phonecode' => '269', 'is_active' => '1'),
            array('id' => '49', 'name' => 'Congo', 'shortname' => 'CG', 'phonecode' => '242', 'is_active' => '1'),
            array('id' => '50', 'name' => 'Congo The Democratic Republic Of', 'shortname' => 'CD', 'phonecode' => '242', 'is_active' => '1'),
            array('id' => '51', 'name' => 'Cook Islands', 'shortname' => 'CK', 'phonecode' => '682', 'is_active' => '1'),
            array('id' => '52', 'name' => 'Costa Rica', 'shortname' => 'CR', 'phonecode' => '506', 'is_active' => '1'),
            array('id' => '53', 'name' => 'Cote D\'Ivoire (Ivory Coast)', 'shortname' => 'CI', 'phonecode' => '225', 'is_active' => '1'),
            array('id' => '54', 'name' => 'Croatia (Hrvatska)', 'shortname' => 'HR', 'phonecode' => '385', 'is_active' => '1'),
            array('id' => '55', 'name' => 'Cuba', 'shortname' => 'CU', 'phonecode' => '53', 'is_active' => '1'),
            array('id' => '56', 'name' => 'Cyprus', 'shortname' => 'CY', 'phonecode' => '357', 'is_active' => '1'),
            array('id' => '57', 'name' => 'Czech Republic', 'shortname' => 'CZ', 'phonecode' => '420', 'is_active' => '1'),
            array('id' => '58', 'name' => 'Denmark', 'shortname' => 'DK', 'phonecode' => '45', 'is_active' => '1'),
            array('id' => '59', 'name' => 'Djibouti', 'shortname' => 'DJ', 'phonecode' => '253', 'is_active' => '1'),
            array('id' => '60', 'name' => 'Dominica', 'shortname' => 'DM', 'phonecode' => '1767', 'is_active' => '1'),
            array('id' => '61', 'name' => 'Dominican Republic', 'shortname' => 'DO', 'phonecode' => '1809', 'is_active' => '1'),
            array('id' => '62', 'name' => 'East Timor', 'shortname' => 'TP', 'phonecode' => '670', 'is_active' => '1'),
            array('id' => '63', 'name' => 'Ecuador', 'shortname' => 'EC', 'phonecode' => '593', 'is_active' => '1'),
            array('id' => '64', 'name' => 'Egypt', 'shortname' => 'EG', 'phonecode' => '20', 'is_active' => '1'),
            array('id' => '65', 'name' => 'El Salvador', 'shortname' => 'SV', 'phonecode' => '503', 'is_active' => '1'),
            array('id' => '66', 'name' => 'Equatorial Guinea', 'shortname' => 'GQ', 'phonecode' => '240', 'is_active' => '1'),
            array('id' => '67', 'name' => 'Eritrea', 'shortname' => 'ER', 'phonecode' => '291', 'is_active' => '1'),
            array('id' => '68', 'name' => 'Estonia', 'shortname' => 'EE', 'phonecode' => '372', 'is_active' => '1'),
            array('id' => '69', 'name' => 'Ethiopia', 'shortname' => 'ET', 'phonecode' => '251', 'is_active' => '1'),
            array('id' => '70', 'name' => 'External Territories of Australia', 'shortname' => 'XA', 'phonecode' => '61', 'is_active' => '1'),
            array('id' => '71', 'name' => 'Falkland Islands', 'shortname' => 'FK', 'phonecode' => '500', 'is_active' => '1'),
            array('id' => '72', 'name' => 'Faroe Islands', 'shortname' => 'FO', 'phonecode' => '298', 'is_active' => '1'),
            array('id' => '73', 'name' => 'Fiji Islands', 'shortname' => 'FJ', 'phonecode' => '679', 'is_active' => '1'),
            array('id' => '74', 'name' => 'Finland', 'shortname' => 'FI', 'phonecode' => '358', 'is_active' => '1'),
            array('id' => '75', 'name' => 'France', 'shortname' => 'FR', 'phonecode' => '33', 'is_active' => '1'),
            array('id' => '76', 'name' => 'French Guiana', 'shortname' => 'GF', 'phonecode' => '594', 'is_active' => '1'),
            array('id' => '77', 'name' => 'French Polynesia', 'shortname' => 'PF', 'phonecode' => '689', 'is_active' => '1'),
            array('id' => '78', 'name' => 'French Southern Territories', 'shortname' => 'TF', 'phonecode' => '0', 'is_active' => '1'),
            array('id' => '79', 'name' => 'Gabon', 'shortname' => 'GA', 'phonecode' => '241', 'is_active' => '1'),
            array('id' => '80', 'name' => 'Gambia The', 'shortname' => 'GM', 'phonecode' => '220', 'is_active' => '1'),
            array('id' => '81', 'name' => 'Georgia', 'shortname' => 'GE', 'phonecode' => '995', 'is_active' => '1'),
            array('id' => '82', 'name' => 'Germany', 'shortname' => 'DE', 'phonecode' => '49', 'is_active' => '1'),
            array('id' => '83', 'name' => 'Ghana', 'shortname' => 'GH', 'phonecode' => '233', 'is_active' => '1'),
            array('id' => '84', 'name' => 'Gibraltar', 'shortname' => 'GI', 'phonecode' => '350', 'is_active' => '1'),
            array('id' => '85', 'name' => 'Greece', 'shortname' => 'GR', 'phonecode' => '30', 'is_active' => '1'),
            array('id' => '86', 'name' => 'Greenland', 'shortname' => 'GL', 'phonecode' => '299', 'is_active' => '1'),
            array('id' => '87', 'name' => 'Grenada', 'shortname' => 'GD', 'phonecode' => '1473', 'is_active' => '1'),
            array('id' => '88', 'name' => 'Guadeloupe', 'shortname' => 'GP', 'phonecode' => '590', 'is_active' => '1'),
            array('id' => '89', 'name' => 'Guam', 'shortname' => 'GU', 'phonecode' => '1671', 'is_active' => '1'),
            array('id' => '90', 'name' => 'Guatemala', 'shortname' => 'GT', 'phonecode' => '502', 'is_active' => '1'),
            array('id' => '91', 'name' => 'Guernsey and Alderney', 'shortname' => 'XU', 'phonecode' => '44', 'is_active' => '1'),
            array('id' => '92', 'name' => 'Guinea', 'shortname' => 'GN', 'phonecode' => '224', 'is_active' => '1'),
            array('id' => '93', 'name' => 'Guinea-Bissau', 'shortname' => 'GW', 'phonecode' => '245', 'is_active' => '1'),
            array('id' => '94', 'name' => 'Guyana', 'shortname' => 'GY', 'phonecode' => '592', 'is_active' => '1'),
            array('id' => '95', 'name' => 'Haiti', 'shortname' => 'HT', 'phonecode' => '509', 'is_active' => '1'),
            array('id' => '96', 'name' => 'Heard and McDonald Islands', 'shortname' => 'HM', 'phonecode' => '0', 'is_active' => '1'),
            array('id' => '97', 'name' => 'Honduras', 'shortname' => 'HN', 'phonecode' => '504', 'is_active' => '1'),
            array('id' => '98', 'name' => 'Hong Kong S.A.R.', 'shortname' => 'HK', 'phonecode' => '852', 'is_active' => '1'),
            array('id' => '99', 'name' => 'Hungary', 'shortname' => 'HU', 'phonecode' => '36', 'is_active' => '1'),
            array('id' => '100', 'name' => 'Iceland', 'shortname' => 'IS', 'phonecode' => '354', 'is_active' => '1'),
            array('id' => '101', 'name' => 'India', 'shortname' => 'IN', 'phonecode' => '91', 'is_active' => '1'),
            array('id' => '102', 'name' => 'Indonesia', 'shortname' => 'ID', 'phonecode' => '62', 'is_active' => '1'),
            array('id' => '103', 'name' => 'Iran', 'shortname' => 'IR', 'phonecode' => '98', 'is_active' => '1'),
            array('id' => '104', 'name' => 'Iraq', 'shortname' => 'IQ', 'phonecode' => '964', 'is_active' => '1'),
            array('id' => '105', 'name' => 'Ireland', 'shortname' => 'IE', 'phonecode' => '353', 'is_active' => '1'),
            array('id' => '106', 'name' => 'Israel', 'shortname' => 'IL', 'phonecode' => '972', 'is_active' => '1'),
            array('id' => '107', 'name' => 'Italy', 'shortname' => 'IT', 'phonecode' => '39', 'is_active' => '1'),
            array('id' => '108', 'name' => 'Jamaica', 'shortname' => 'JM', 'phonecode' => '1876', 'is_active' => '1'),
            array('id' => '109', 'name' => 'Japan', 'shortname' => 'JP', 'phonecode' => '81', 'is_active' => '1'),
            array('id' => '110', 'name' => 'Jersey', 'shortname' => 'XJ', 'phonecode' => '44', 'is_active' => '1'),
            array('id' => '111', 'name' => 'Jordan', 'shortname' => 'JO', 'phonecode' => '962', 'is_active' => '1'),
            array('id' => '112', 'name' => 'Kazakhstan', 'shortname' => 'KZ', 'phonecode' => '7', 'is_active' => '1'),
            array('id' => '113', 'name' => 'Kenya', 'shortname' => 'KE', 'phonecode' => '254', 'is_active' => '1'),
            array('id' => '114', 'name' => 'Kiribati', 'shortname' => 'KI', 'phonecode' => '686', 'is_active' => '1'),
            array('id' => '115', 'name' => 'Korea North', 'shortname' => 'KP', 'phonecode' => '850', 'is_active' => '1'),
            array('id' => '116', 'name' => 'Korea South', 'shortname' => 'KR', 'phonecode' => '82', 'is_active' => '1'),
            array('id' => '117', 'name' => 'Kuwait', 'shortname' => 'KW', 'phonecode' => '965', 'is_active' => '1'),
            array('id' => '118', 'name' => 'Kyrgyzstan', 'shortname' => 'KG', 'phonecode' => '996', 'is_active' => '1'),
            array('id' => '119', 'name' => 'Laos', 'shortname' => 'LA', 'phonecode' => '856', 'is_active' => '1'),
            array('id' => '120', 'name' => 'Latvia', 'shortname' => 'LV', 'phonecode' => '371', 'is_active' => '1'),
            array('id' => '121', 'name' => 'Lebanon', 'shortname' => 'LB', 'phonecode' => '961', 'is_active' => '1'),
            array('id' => '122', 'name' => 'Lesotho', 'shortname' => 'LS', 'phonecode' => '266', 'is_active' => '1'),
            array('id' => '123', 'name' => 'Liberia', 'shortname' => 'LR', 'phonecode' => '231', 'is_active' => '1'),
            array('id' => '124', 'name' => 'Libya', 'shortname' => 'LY', 'phonecode' => '218', 'is_active' => '1'),
            array('id' => '125', 'name' => 'Liechtenstein', 'shortname' => 'LI', 'phonecode' => '423', 'is_active' => '1'),
            array('id' => '126', 'name' => 'Lithuania', 'shortname' => 'LT', 'phonecode' => '370', 'is_active' => '1'),
            array('id' => '127', 'name' => 'Luxembourg', 'shortname' => 'LU', 'phonecode' => '352', 'is_active' => '1'),
            array('id' => '128', 'name' => 'Macau S.A.R.', 'shortname' => 'MO', 'phonecode' => '853', 'is_active' => '1'),
            array('id' => '129', 'name' => 'Macedonia', 'shortname' => 'MK', 'phonecode' => '389', 'is_active' => '1'),
            array('id' => '130', 'name' => 'Madagascar', 'shortname' => 'MG', 'phonecode' => '261', 'is_active' => '1'),
            array('id' => '131', 'name' => 'Malawi', 'shortname' => 'MW', 'phonecode' => '265', 'is_active' => '1'),
            array('id' => '132', 'name' => 'Malaysia', 'shortname' => 'MY', 'phonecode' => '60', 'is_active' => '1'),
            array('id' => '133', 'name' => 'Maldives', 'shortname' => 'MV', 'phonecode' => '960', 'is_active' => '1'),
            array('id' => '134', 'name' => 'Mali', 'shortname' => 'ML', 'phonecode' => '223', 'is_active' => '1'),
            array('id' => '135', 'name' => 'Malta', 'shortname' => 'MT', 'phonecode' => '356', 'is_active' => '1'),
            array('id' => '136', 'name' => 'Man (Isle of)', 'shortname' => 'XM', 'phonecode' => '44', 'is_active' => '1'),
            array('id' => '137', 'name' => 'Marshall Islands', 'shortname' => 'MH', 'phonecode' => '692', 'is_active' => '1'),
            array('id' => '138', 'name' => 'Martinique', 'shortname' => 'MQ', 'phonecode' => '596', 'is_active' => '1'),
            array('id' => '139', 'name' => 'Mauritania', 'shortname' => 'MR', 'phonecode' => '222', 'is_active' => '1'),
            array('id' => '140', 'name' => 'Mauritius', 'shortname' => 'MU', 'phonecode' => '230', 'is_active' => '1'),
            array('id' => '141', 'name' => 'Mayotte', 'shortname' => 'YT', 'phonecode' => '269', 'is_active' => '1'),
            array('id' => '142', 'name' => 'Mexico', 'shortname' => 'MX', 'phonecode' => '52', 'is_active' => '1'),
            array('id' => '143', 'name' => 'Micronesia', 'shortname' => 'FM', 'phonecode' => '691', 'is_active' => '1'),
            array('id' => '144', 'name' => 'Moldova', 'shortname' => 'MD', 'phonecode' => '373', 'is_active' => '1'),
            array('id' => '145', 'name' => 'Monaco', 'shortname' => 'MC', 'phonecode' => '377', 'is_active' => '1'),
            array('id' => '146', 'name' => 'Mongolia', 'shortname' => 'MN', 'phonecode' => '976', 'is_active' => '1'),
            array('id' => '147', 'name' => 'Montserrat', 'shortname' => 'MS', 'phonecode' => '1664', 'is_active' => '1'),
            array('id' => '148', 'name' => 'Morocco', 'shortname' => 'MA', 'phonecode' => '212', 'is_active' => '1'),
            array('id' => '149', 'name' => 'Mozambique', 'shortname' => 'MZ', 'phonecode' => '258', 'is_active' => '1'),
            array('id' => '150', 'name' => 'Myanmar', 'shortname' => 'MM', 'phonecode' => '95', 'is_active' => '1'),
            array('id' => '151', 'name' => 'Namibia', 'shortname' => 'NA', 'phonecode' => '264', 'is_active' => '1'),
            array('id' => '152', 'name' => 'Nauru', 'shortname' => 'NR', 'phonecode' => '674', 'is_active' => '1'),
            array('id' => '153', 'name' => 'Nepal', 'shortname' => 'NP', 'phonecode' => '977', 'is_active' => '1'),
            array('id' => '154', 'name' => 'Netherlands Antilles', 'shortname' => 'AN', 'phonecode' => '599', 'is_active' => '1'),
            array('id' => '155', 'name' => 'Netherlands The', 'shortname' => 'NL', 'phonecode' => '31', 'is_active' => '1'),
            array('id' => '156', 'name' => 'New Caledonia', 'shortname' => 'NC', 'phonecode' => '687', 'is_active' => '1'),
            array('id' => '157', 'name' => 'New Zealand', 'shortname' => 'NZ', 'phonecode' => '64', 'is_active' => '1'),
            array('id' => '158', 'name' => 'Nicaragua', 'shortname' => 'NI', 'phonecode' => '505', 'is_active' => '1'),
            array('id' => '159', 'name' => 'Niger', 'shortname' => 'NE', 'phonecode' => '227', 'is_active' => '1'),
            array('id' => '160', 'name' => 'Nigeria', 'shortname' => 'NG', 'phonecode' => '234', 'is_active' => '1'),
            array('id' => '161', 'name' => 'Niue', 'shortname' => 'NU', 'phonecode' => '683', 'is_active' => '1'),
            array('id' => '162', 'name' => 'Norfolk Island', 'shortname' => 'NF', 'phonecode' => '672', 'is_active' => '1'),
            array('id' => '163', 'name' => 'Northern Mariana Islands', 'shortname' => 'MP', 'phonecode' => '1670', 'is_active' => '1'),
            array('id' => '164', 'name' => 'Norway', 'shortname' => 'NO', 'phonecode' => '47', 'is_active' => '1'),
            array('id' => '165', 'name' => 'Oman', 'shortname' => 'OM', 'phonecode' => '968', 'is_active' => '1'),
            array('id' => '166', 'name' => 'Pakistan', 'shortname' => 'PK', 'phonecode' => '92', 'is_active' => '1'),
            array('id' => '167', 'name' => 'Palau', 'shortname' => 'PW', 'phonecode' => '680', 'is_active' => '1'),
            array('id' => '168', 'name' => 'Palestinian Territory Occupied', 'shortname' => 'PS', 'phonecode' => '970', 'is_active' => '1'),
            array('id' => '169', 'name' => 'Panama', 'shortname' => 'PA', 'phonecode' => '507', 'is_active' => '1'),
            array('id' => '170', 'name' => 'Papua new Guinea', 'shortname' => 'PG', 'phonecode' => '675', 'is_active' => '1'),
            array('id' => '171', 'name' => 'Paraguay', 'shortname' => 'PY', 'phonecode' => '595', 'is_active' => '1'),
            array('id' => '172', 'name' => 'Peru', 'shortname' => 'PE', 'phonecode' => '51', 'is_active' => '1'),
            array('id' => '173', 'name' => 'Philippines', 'shortname' => 'PH', 'phonecode' => '63', 'is_active' => '1'),
            array('id' => '174', 'name' => 'Pitcairn Island', 'shortname' => 'PN', 'phonecode' => '0', 'is_active' => '1'),
            array('id' => '175', 'name' => 'Poland', 'shortname' => 'PL', 'phonecode' => '48', 'is_active' => '1'),
            array('id' => '176', 'name' => 'Portugal', 'shortname' => 'PT', 'phonecode' => '351', 'is_active' => '1'),
            array('id' => '177', 'name' => 'Puerto Rico', 'shortname' => 'PR', 'phonecode' => '1787', 'is_active' => '1'),
            array('id' => '178', 'name' => 'Qatar', 'shortname' => 'QA', 'phonecode' => '974', 'is_active' => '1'),
            array('id' => '179', 'name' => 'Reunion', 'shortname' => 'RE', 'phonecode' => '262', 'is_active' => '1'),
            array('id' => '180', 'name' => 'Romania', 'shortname' => 'RO', 'phonecode' => '40', 'is_active' => '1'),
            array('id' => '181', 'name' => 'Russia', 'shortname' => 'RU', 'phonecode' => '70', 'is_active' => '1'),
            array('id' => '182', 'name' => 'Rwanda', 'shortname' => 'RW', 'phonecode' => '250', 'is_active' => '1'),
            array('id' => '183', 'name' => 'Saint Helena', 'shortname' => 'SH', 'phonecode' => '290', 'is_active' => '1'),
            array('id' => '184', 'name' => 'Saint Kitts And Nevis', 'shortname' => 'KN', 'phonecode' => '1869', 'is_active' => '1'),
            array('id' => '185', 'name' => 'Saint Lucia', 'shortname' => 'LC', 'phonecode' => '1758', 'is_active' => '1'),
            array('id' => '186', 'name' => 'Saint Pierre and Miquelon', 'shortname' => 'PM', 'phonecode' => '508', 'is_active' => '1'),
            array('id' => '187', 'name' => 'Saint Vincent And The Grenadines', 'shortname' => 'VC', 'phonecode' => '1784', 'is_active' => '1'),
            array('id' => '188', 'name' => 'Samoa', 'shortname' => 'WS', 'phonecode' => '684', 'is_active' => '1'),
            array('id' => '189', 'name' => 'San Marino', 'shortname' => 'SM', 'phonecode' => '378', 'is_active' => '1'),
            array('id' => '190', 'name' => 'Sao Tome and Principe', 'shortname' => 'ST', 'phonecode' => '239', 'is_active' => '1'),
            array('id' => '191', 'name' => 'Saudi Arabia', 'shortname' => 'SA', 'phonecode' => '966', 'is_active' => '1'),
            array('id' => '192', 'name' => 'Senegal', 'shortname' => 'SN', 'phonecode' => '221', 'is_active' => '1'),
            array('id' => '193', 'name' => 'Serbia', 'shortname' => 'RS', 'phonecode' => '381', 'is_active' => '1'),
            array('id' => '194', 'name' => 'Seychelles', 'shortname' => 'SC', 'phonecode' => '248', 'is_active' => '1'),
            array('id' => '195', 'name' => 'Sierra Leone', 'shortname' => 'SL', 'phonecode' => '232', 'is_active' => '1'),
            array('id' => '196', 'name' => 'Singapore', 'shortname' => 'SG', 'phonecode' => '65', 'is_active' => '1'),
            array('id' => '197', 'name' => 'Slovakia', 'shortname' => 'SK', 'phonecode' => '421', 'is_active' => '1'),
            array('id' => '198', 'name' => 'Slovenia', 'shortname' => 'SI', 'phonecode' => '386', 'is_active' => '1'),
            array('id' => '199', 'name' => 'Smaller Territories of the UK', 'shortname' => 'XG', 'phonecode' => '44', 'is_active' => '1'),
            array('id' => '200', 'name' => 'Solomon Islands', 'shortname' => 'SB', 'phonecode' => '677', 'is_active' => '1'),
            array('id' => '201', 'name' => 'Somalia', 'shortname' => 'SO', 'phonecode' => '252', 'is_active' => '1'),
            array('id' => '202', 'name' => 'South Africa', 'shortname' => 'ZA', 'phonecode' => '27', 'is_active' => '1'),
            array('id' => '203', 'name' => 'South Georgia', 'shortname' => 'GS', 'phonecode' => '0', 'is_active' => '1'),
            array('id' => '204', 'name' => 'South Sudan', 'shortname' => 'SS', 'phonecode' => '211', 'is_active' => '1'),
            array('id' => '205', 'name' => 'Spain', 'shortname' => 'ES', 'phonecode' => '34', 'is_active' => '1'),
            array('id' => '206', 'name' => 'Sri Lanka', 'shortname' => 'LK', 'phonecode' => '94', 'is_active' => '1'),
            array('id' => '207', 'name' => 'Sudan', 'shortname' => 'SD', 'phonecode' => '249', 'is_active' => '1'),
            array('id' => '208', 'name' => 'Suriname', 'shortname' => 'SR', 'phonecode' => '597', 'is_active' => '1'),
            array('id' => '209', 'name' => 'Svalbard And Jan Mayen Islands', 'shortname' => 'SJ', 'phonecode' => '47', 'is_active' => '1'),
            array('id' => '210', 'name' => 'Swaziland', 'shortname' => 'SZ', 'phonecode' => '268', 'is_active' => '1'),
            array('id' => '211', 'name' => 'Sweden', 'shortname' => 'SE', 'phonecode' => '46', 'is_active' => '1'),
            array('id' => '212', 'name' => 'Switzerland', 'shortname' => 'CH', 'phonecode' => '41', 'is_active' => '1'),
            array('id' => '213', 'name' => 'Syria', 'shortname' => 'SY', 'phonecode' => '963', 'is_active' => '1'),
            array('id' => '214', 'name' => 'Taiwan', 'shortname' => 'TW', 'phonecode' => '886', 'is_active' => '1'),
            array('id' => '215', 'name' => 'Tajikistan', 'shortname' => 'TJ', 'phonecode' => '992', 'is_active' => '1'),
            array('id' => '216', 'name' => 'Tanzania', 'shortname' => 'TZ', 'phonecode' => '255', 'is_active' => '1'),
            array('id' => '217', 'name' => 'Thailand', 'shortname' => 'TH', 'phonecode' => '66', 'is_active' => '1'),
            array('id' => '218', 'name' => 'Togo', 'shortname' => 'TG', 'phonecode' => '228', 'is_active' => '1'),
            array('id' => '219', 'name' => 'Tokelau', 'shortname' => 'TK', 'phonecode' => '690', 'is_active' => '1'),
            array('id' => '220', 'name' => 'Tonga', 'shortname' => 'TO', 'phonecode' => '676', 'is_active' => '1'),
            array('id' => '221', 'name' => 'Trinidad And Tobago', 'shortname' => 'TT', 'phonecode' => '1868', 'is_active' => '1'),
            array('id' => '222', 'name' => 'Tunisia', 'shortname' => 'TN', 'phonecode' => '216', 'is_active' => '1'),
            array('id' => '223', 'name' => 'Turkey', 'shortname' => 'TR', 'phonecode' => '90', 'is_active' => '1'),
            array('id' => '224', 'name' => 'Turkmenistan', 'shortname' => 'TM', 'phonecode' => '7370', 'is_active' => '1'),
            array('id' => '225', 'name' => 'Turks And Caicos Islands', 'shortname' => 'TC', 'phonecode' => '1649', 'is_active' => '1'),
            array('id' => '226', 'name' => 'Tuvalu', 'shortname' => 'TV', 'phonecode' => '688', 'is_active' => '1'),
            array('id' => '227', 'name' => 'Uganda', 'shortname' => 'UG', 'phonecode' => '256', 'is_active' => '1'),
            array('id' => '228', 'name' => 'Ukraine', 'shortname' => 'UA', 'phonecode' => '380', 'is_active' => '1'),
            array('id' => '229', 'name' => 'United Arab Emirates', 'shortname' => 'AE', 'phonecode' => '971', 'is_active' => '1'),
            array('id' => '230', 'name' => 'United Kingdom', 'shortname' => 'GB', 'phonecode' => '44', 'is_active' => '1'),
            array('id' => '231', 'name' => 'United States', 'shortname' => 'US', 'phonecode' => '1', 'is_active' => '1'),
            array('id' => '232', 'name' => 'United States Minor Outlying Islands', 'shortname' => 'UM', 'phonecode' => '1', 'is_active' => '1'),
            array('id' => '233', 'name' => 'Uruguay', 'shortname' => 'UY', 'phonecode' => '598', 'is_active' => '1'),
            array('id' => '234', 'name' => 'Uzbekistan', 'shortname' => 'UZ', 'phonecode' => '998', 'is_active' => '1'),
            array('id' => '235', 'name' => 'Vanuatu', 'shortname' => 'VU', 'phonecode' => '678', 'is_active' => '1'),
            array('id' => '236', 'name' => 'Vatican City State (Holy See)', 'shortname' => 'VA', 'phonecode' => '39', 'is_active' => '1'),
            array('id' => '237', 'name' => 'Venezuela', 'shortname' => 'VE', 'phonecode' => '58', 'is_active' => '1'),
            array('id' => '238', 'name' => 'Vietnam', 'shortname' => 'VN', 'phonecode' => '84', 'is_active' => '1'),
            array('id' => '239', 'name' => 'Virgin Islands (British)', 'shortname' => 'VG', 'phonecode' => '1284', 'is_active' => '1'),
            array('id' => '240', 'name' => 'Virgin Islands (US)', 'shortname' => 'VI', 'phonecode' => '1340', 'is_active' => '1'),
            array('id' => '241', 'name' => 'Wallis And Futuna Islands', 'shortname' => 'WF', 'phonecode' => '681', 'is_active' => '1'),
            array('id' => '242', 'name' => 'Western Sahara', 'shortname' => 'EH', 'phonecode' => '212', 'is_active' => '1'),
            array('id' => '243', 'name' => 'Yemen', 'shortname' => 'YE', 'phonecode' => '967', 'is_active' => '1'),
            array('id' => '244', 'name' => 'Yugoslavia', 'shortname' => 'YU', 'phonecode' => '38', 'is_active' => '1'),
            array('id' => '245', 'name' => 'Zambia', 'shortname' => 'ZM', 'phonecode' => '260', 'is_active' => '1'),
            array('id' => '246', 'name' => 'Zimbabwe', 'shortname' => 'ZW', 'phonecode' => '263', 'is_active' => '1')
        );

        \DB::table('countries')->insert($countries);
    }
}
